### PR TITLE
New Class "qStr", replaces string arrays

### PR DESCRIPTION
**Pull request by Blank-One**
objects of the new class are replacement for char data type arrays to be used as strings. It provides much easier methods of accessing, editing and comparing strings i.e. unary operators like +, = can be used and logical operators ( ==, != ) can also be used. single blocks can be accessed just like usual arrays []

In process of adding features of all paragraph, animation and encryption classes

- center_align currently has an issue

- other functions have been deleted. they will be added on later

- class name might be changed in the future

### CODE REVIEW

**Comment by MFReaper** [comment]
Center aligning functional now

**Comment by MFReaper** [comment]
_Animation Class is now being merged with the new style_

Typewriting animation is functional, random animation too still be written

**Comment by Yash-Garg** [comment]
Noice re

**Comment by Blank-One** [comment]
The dev was mostly fine, but it was limited due to limit of max length

another version will be uploaded with better handling of this issue

**Comment by Yash-Garg** [comment]
Ono wtf

**Pull request closed without merging**
